## Import Library

In [36]:
import numpy as np
import cv2# 202331150_Caesar Albaari Azatin

## Membaca Citra

In [37]:
citra = cv2.imread('buah tin.jpg') # 202331150_Caesar Albaari Azatin

In [38]:
cv2.imshow("citra asli", citra)
cv2.waitKey()
cv2.destroyAllWindows()# 202331150_Caesar Albaari Azatin

## Dimesi Citra

In [39]:
print(citra.shape)
print(citra.dtype)# 202331150_Caesar Albaari Azatin

(270, 267, 3)
uint8


## Splitting Citra RGB/BGR

In [40]:
b = citra[:,:,0]
g = citra[:,:,1]
r = citra[:,:,2]# 202331150_Caesar Albaari Azatin

## RGB to Grayscale

In [41]:
panjang = len(citra)
lebar = len(citra[0])

citra_gray = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar) :
        citra_gray[i,j] = 0.2989 * r[i,j] +0.1141 * b[i,j]
        
citra_gray = citra_gray.astype(np.uint8)

cv2.imshow("citra grayscale", citra_gray)
cv2.waitKey()
cv2.destroyAllWindows() # 202331150_Caesar Albaari Azatin

In [42]:
print(citra)# 202331150_Caesar Albaari Azatin

[[[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 ...

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]]


In [43]:
print(citra_gray)# 202331150_Caesar Albaari Azatin

[[104 104 104 ... 104 104 104]
 [104 104 104 ... 104 104 104]
 [104 104 104 ... 104 104 104]
 ...
 [104 104 104 ... 104 104 104]
 [104 104 104 ... 104 104 104]
 [104 104 104 ... 104 104 104]]


## Grayscale to Binary

In [44]:
panjang = len(citra)
lebar = len(citra[0])

ambang = 90

citra_biner = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        if citra_gray[i,j] >= ambang:
            citra_biner[i,j] = 1  #putih
        else:
            citra_biner[i,j] = 0  #hitam

                
cv2.imshow("citra binary", citra_biner)
cv2.waitKey()
cv2.destroyAllWindows() # 202331150_Caesar Albaari Azatin

In [45]:
print(citra_gray)# 202331150_Caesar Albaari Azatin

[[104 104 104 ... 104 104 104]
 [104 104 104 ... 104 104 104]
 [104 104 104 ... 104 104 104]
 ...
 [104 104 104 ... 104 104 104]
 [104 104 104 ... 104 104 104]
 [104 104 104 ... 104 104 104]]


In [46]:
print(citra_biner)# 202331150_Caesar Albaari Azatin

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [47]:
print(citra_biner[50,50])# 202331150_Caesar Albaari Azatin

1.0
